window.apnExeFile = {
  CTXT: { layoutID: 1 },
  property: {
    ver: "1.0",
    denyCloneLocal: true,
    allowClearTimeout: true,
    denyWidgetStartEvent: true,
    denyInvisibleIntersect: true,
    fixBookStartProcess: true,
    allowImmediateContentLoad: true,
    fixBookPageLayout: true,
    fixOveralyRun: true,
    fix2SideBookCase1: true,
    fixWgtPut: true,
    fixScreenPadding: true,
    corpID: "",
    accountID: "",
    title: "[샘플] 청소년기의 이해",
    categoryId: "",
    type: "P",
    id: "ca602ce698ee4831a277660caac03c38",
    createDate: "20250419113305",
  },
  pages: {
    1: {
      UI: { title: "Page 1", order: 1 },
      objects: {
        "9A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 100000001,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIb98bf50c83ee431591ed18d699e981e6_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1531, h: 984 },
            cx: 0,
            cy: 0,
          },
        },
        "836A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329754,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIde351afe579245cdbe4d7b930dfe5600_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
              },
            },
          },
          init: {
            position: { x: 477, y: 801 },
            shape: { type: 1, w: 220, h: 71 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              order: 0,
              target: { objectID: "1244A1_" },
              set: { visibility: "Show" },
            },
          ],
        },
        "987A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329764,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI3a3e46fb254b4bce88cab0280b001d8f_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1153, y: 802 },
            shape: { type: 1, w: 220, h: 71 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              order: 0,
              target: { objectID: "1495A1_" },
              set: { visibility: "Show" },
            },
          ],
        },
        "1244A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101329770,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$click_popup", c: false },
            },
          },
          init: {
            position: { x: 68, y: 148.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: {
            layers: { 1: { title: "Layer1", id: "1254A1_" } },
            layerIndex: 1,
            children: ["1254A1_"],
          },
        },
        "1254A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101329771 },
          init: {
            position: { x: 68, y: 148.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: [
              "1344A1_",
              "1345A1_",
              "1346A1_",
              "1347A1_",
              "1348A1_",
              "1349A1_",
            ],
          },
        },
        "1344A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329780,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI147fed4bd28f47438b08ea0b9c8b5ebe_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 68, y: 148.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
        },
        "1345A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329781,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI8232589dcdba45ccab4065ddc17af621_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$click_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 126, y: 319.5 },
            shape: { type: 1, w: 235, h: 235 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1345A1_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
          ],
        },
        "1346A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329782,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIcec2bd6c2ae044f68c0da3d16864fc02_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$click_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 447, y: 319.5 },
            shape: { type: 1, w: 235, h: 235 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1346A1_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
          ],
        },
        "1347A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329783,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI608416d1394e49d791e07e807d98c652_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$click_3",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 132, y: 592.5 },
            shape: { type: 1, w: 235, h: 235 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1347A1_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
          ],
        },
        "1348A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329784,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI8de8665ea9304b37aae67e1656b8c2fc_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$click_4",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 447, y: 592.5 },
            shape: { type: 1, w: 235, h: 235 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1348A1_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
          ],
        },
        "1349A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329785,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.roundRect",
              wgtTitle: "Round Rectangle",
              styles: {
                O: true,
                U: true,
                F: 4,
                G: 4,
                H: 4,
                I: 4,
                A: "rgba(255,255,255,0)",
                C: 0,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 667, y: 169.5 },
            shape: { type: 1, w: 51.53846153846155, h: 50 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1244A1_" },
              order: 0,
              ui: {},
              set: { visibility: "Hide" },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1345A1_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
              ui: {},
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1346A1_" },
              order: 2,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1347A1_" },
              order: 3,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1348A1_" },
              order: 4,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
          ],
        },
        "1495A1_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101329794,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$type_popup", c: false },
              lockType: 0,
            },
          },
          init: {
            position: { x: 796, y: 148.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["1496A1_"],
            layers: { 1: { title: "Layer1", id: "1496A1_" } },
            layerIndex: 1,
          },
        },
        "1496A1_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101329795 },
          init: {
            position: { x: 796, y: 148.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["1497A1_", "1498A1_", "1499A1_", "1500A1_"] },
        },
        "1497A1_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329796,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI79679dce96fd46e6aa6f6e75f66dbc7a_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 796, y: 148.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
        },
        "1498A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329797,
            data: {
              properties: {
                state: "normal",
                attrs: { ime: "T", ty: "", mxl: "16" },
              },
              wgtID: "ux.wgt.inputText",
              wgtTitle: "Input Text <HTML>",
              styles: { C: 0, A: null, R: "left", K: "30px", k: "it$text_1" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 890, y: 534.5 },
            shape: { type: 1, w: 473, h: 66 },
            cx: 0,
            cy: 0,
          },
          SPT: {},
        },
        "1499A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329798,
            data: {
              properties: {
                state: "normal",
                attrs: { ime: "T", ty: "", mxl: "16" },
              },
              wgtID: "ux.wgt.inputText",
              wgtTitle: "Input Text <HTML>",
              styles: { C: 0, A: null, R: "left", K: "30px", k: "it$text_2" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 890, y: 713.5 },
            shape: { type: 1, w: 473, h: 66 },
            cx: 0,
            cy: 0,
          },
        },
        "1500A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329799,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.roundRect",
              wgtTitle: "Round Rectangle",
              styles: {
                O: true,
                U: true,
                F: 4,
                G: 4,
                H: 4,
                I: 4,
                A: "rgba(255,255,255,0)",
                C: 0,
                k: "rr$type_exit",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1394, y: 167.5 },
            shape: { type: 1, w: 51.53846153846155, h: 50 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1495A1_" },
              set: { visibility: "Hide" },
              order: 0,
              ui: {},
            },
          ],
          SPT: {
            tapStart:
              '$W("it$text_1").set("value","");\n$W("it$text_2").set("value","");',
          },
        },
        "1719A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329801,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.rect",
              wgtTitle: "Rectangle",
              styles: { O: true, C: 0, A: "rgba(255,255,255,0)", j: "pointer" },
            },
          },
          init: {
            position: { x: 1476, y: 482 },
            shape: { type: 1, w: 43, h: 43 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "LTP",
              event: "tapStart",
              from: { pageID: "1", objectID: "1719A1_" },
              to: { type: "1", reset: true, pageID: "2" },
              transit: { duration: 0 },
              order: 0,
            },
          ],
        },
        "1730A1_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329802,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.rect",
              wgtTitle: "Rectangle",
              styles: { O: true, C: 0, A: "rgba(255,255,255,0)", j: "pointer" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 13, y: 471 },
            shape: { type: 1, w: 43, h: 43 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "LTP",
              event: "tapStart",
              from: { pageID: "1", objectID: "1730A1_" },
              to: { type: "1", reset: true, pageID: "2" },
              transit: { duration: 0 },
              order: 0,
            },
          ],
        },
      },
      module: "apn.CFlowPage",
      BG: { fillStyle: "#ffffff" },
      SPT: { pageRun: '$W("it$text_1").run("focus",true);' },
    },
    2: {
      UI: { title: "Page 2", order: 3 },
      objects: {
        "24A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 100000002,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI2a8d33d11e1a488292773e74c71dec97_png",
                C: 0,
                A: "transparent",
                a: false,
              },
            },
          },
          init: {
            position: { x: 0, y: 0 },
            shape: { type: 1, w: 1531, h: 984 },
            cx: 0,
            cy: 0,
          },
        },
        "511A2_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 100000052,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.roundRect",
              wgtTitle: "Round Rectangle",
              styles: {
                O: true,
                U: true,
                F: 30,
                G: 30,
                H: 30,
                I: 30,
                A: "rgba(255,255,255,0)",
                C: 0,
              },
            },
          },
          init: {
            position: { x: 422, y: 802 },
            shape: { type: 1, w: 218, h: 71 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              order: 0,
              target: { objectID: "1772A2_" },
              set: { visibility: "Show" },
            },
          ],
        },
        "1735A2_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329803,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.rect",
              wgtTitle: "Rectangle",
              styles: { O: true, C: 0, A: "rgba(255,255,255,0)", j: "pointer" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 14, y: 470 },
            shape: { type: 1, w: 43, h: 43 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "LTP",
              event: "tapStart",
              from: { pageID: "2", objectID: "1735A2_" },
              to: { type: "1", reset: true, pageID: "1" },
              transit: { duration: 0 },
              order: 0,
            },
          ],
        },
        "1746A2_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329804,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.rect",
              wgtTitle: "Rectangle",
              styles: { O: true, C: 0, A: "rgba(255,255,255,0)", j: "pointer" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1474, y: 484 },
            shape: { type: 1, w: 43, h: 43 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "LTP",
              event: "tapStart",
              from: { pageID: "2", objectID: "1746A2_" },
              to: { type: "1", reset: true, pageID: "1" },
              transit: { duration: 0 },
              order: 0,
            },
          ],
        },
        "1772A2_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101329805,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$line_popup", c: false },
              lockType: 0,
            },
          },
          init: {
            position: { x: 62, y: 153 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["1773A2_"],
            layers: { 1: { title: "Layer1", id: "1773A2_" } },
            layerIndex: 1,
          },
        },
        "1773A2_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101329806 },
          init: {
            position: { x: 62, y: 153 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: [
              "1774A2_",
              "1775A2_",
              "1776A2_",
              "1777A2_",
              "1778A2_",
              "1779A2_",
              "1780A2_",
              "1781A2_",
              "1782A2_",
              "1783A2_",
              "1784A2_",
              "1785A2_",
              "1786A2_",
              "1787A2_",
            ],
          },
        },
        "1774A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329807,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI94b14c0292b140b5b5cc3b9714d9415a_png",
                C: 0,
                a: false,
                A: "rgba(255,255,255,0)",
                k: "i$reset_1",
                c: 1,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 62, y: 153 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
        },
        "1775A2_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329808,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.rect",
              wgtTitle: "Rectangle",
              styles: { O: true, A: "#f1dab9", C: 0, c: 1 },
              lockType: 0,
            },
          },
          init: {
            position: { x: 325, y: 354 },
            shape: { type: 1, w: 185, h: 461 },
            cx: 0,
            cy: 0,
          },
        },
        "1776A2_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329809,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.roundRect",
              wgtTitle: "Round Rectangle",
              styles: {
                O: true,
                U: true,
                F: 4,
                G: 4,
                H: 4,
                I: 4,
                A: "rgba(255,255,255,0)",
                C: 0,
                k: "rr$line_exit",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 660, y: 173 },
            shape: { type: 1, w: 51.53846153846155, h: 50 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1772A2_" },
              set: { visibility: "Hide" },
              order: 0,
            },
          ],
        },
        "1777A2_": {
          module: "apn.CItrAreaRect",
          create: {
            type: 16777728,
            zIndex: 101329810,
            data: {
              properties: { attrs: { hp: "N" } },
              wgtID: "apn.wgt.itrAreaRect",
              wgtTitle: "Interaction Area",
              styles: { k: "ia$1_1" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 479, y: 540 },
            shape: { type: 1, w: 30, h: 30 },
            cx: 0,
            cy: 0,
          },
        },
        "1778A2_": {
          module: "apn.CItrAreaRect",
          create: {
            type: 16777728,
            zIndex: 101329811,
            data: {
              properties: { attrs: { hp: "N" } },
              wgtID: "apn.wgt.itrAreaRect",
              wgtTitle: "Interaction Area",
              styles: { k: "ia$1_2" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 479, y: 715 },
            shape: { type: 1, w: 30, h: 30 },
            cx: 0,
            cy: 0,
          },
        },
        "1779A2_": {
          module: "apn.CItrAreaRect",
          create: {
            type: 16777728,
            zIndex: 101329812,
            data: {
              properties: { attrs: { hp: "N" } },
              wgtID: "apn.wgt.itrAreaRect",
              wgtTitle: "Interaction Area",
              styles: { k: "ia$1_3" },
              lockType: 0,
            },
          },
          init: {
            position: { x: 479, y: 385 },
            shape: { type: 1, w: 30, h: 30 },
            cx: 0,
            cy: 0,
          },
        },
        "1780A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329813,
            data: {
              properties: {
                attrs: {
                  cfg: {
                    images: {
                      handle: {
                        mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                      },
                      base: {
                        mediaID: "RI1d0e79fcbc1a418c986ba7e91094d35f_png",
                      },
                    },
                    lineColor: "#e99e62",
                    lineWidth: 9,
                    basePos: "",
                    dlVer: 2,
                  },
                  lineColor: "#e99e62",
                },
              },
              wgtID: "edu.wgt.dragLine",
              wgtTitle: "Drag Line",
              styles: {
                mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                d: true,
                e: true,
                a: false,
                k: "dl$1_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 329, y: 390 },
            shape: { type: 1, w: 20, h: 20 },
            cx: 0,
            cy: 0,
          },
          SPT: {},
        },
        "1781A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329814,
            data: {
              properties: {
                attrs: {
                  cfg: {
                    images: {
                      handle: {
                        mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                      },
                      base: {
                        mediaID: "RI1d0e79fcbc1a418c986ba7e91094d35f_png",
                      },
                    },
                    lineColor: "#e99e62",
                    lineWidth: 9,
                    basePos: "",
                    dlVer: 2,
                  },
                  lineColor: "#e99e62",
                },
              },
              wgtID: "edu.wgt.dragLine",
              wgtTitle: "Drag Line",
              styles: {
                mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                d: true,
                e: true,
                a: false,
                k: "dl$1_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 329, y: 545 },
            shape: { type: 1, w: 20, h: 20 },
            cx: 0,
            cy: 0,
          },
        },
        "1782A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329815,
            data: {
              properties: {
                attrs: {
                  cfg: {
                    images: {
                      handle: {
                        mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                      },
                      base: {
                        mediaID: "RI1d0e79fcbc1a418c986ba7e91094d35f_png",
                      },
                    },
                    lineColor: "#e99e62",
                    lineWidth: 9,
                    basePos: "",
                    dlVer: 2,
                  },
                  lineColor: "#e99e62",
                },
              },
              wgtID: "edu.wgt.dragLine",
              wgtTitle: "Drag Line",
              styles: {
                mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                d: true,
                e: true,
                a: false,
                k: "dl$1_3",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 329, y: 720 },
            shape: { type: 1, w: 20, h: 20 },
            cx: 0,
            cy: 0,
          },
        },
        "1783A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329816,
            data: {
              properties: {
                attrs: {
                  cfg: {
                    images: {
                      handle: {
                        mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                      },
                      base: {
                        mediaID: "RI1d0e79fcbc1a418c986ba7e91094d35f_png",
                      },
                    },
                    lineColor: "#e99e62",
                    lineWidth: 9,
                    basePos: "",
                    dlVer: 2,
                  },
                  lineColor: "#e99e62",
                },
              },
              wgtID: "edu.wgt.dragLine",
              wgtTitle: "Drag Line",
              styles: {
                mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                a: false,
                k: "dl$2_1",
                j: "default",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 484, y: 390 },
            shape: { type: 1, w: 20, h: 20 },
            cx: 0,
            cy: 0,
          },
        },
        "1784A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329817,
            data: {
              properties: {
                attrs: {
                  cfg: {
                    images: {
                      handle: {
                        mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                      },
                      base: {
                        mediaID: "RI1d0e79fcbc1a418c986ba7e91094d35f_png",
                      },
                    },
                    lineColor: "#e99e62",
                    lineWidth: 9,
                    basePos: "",
                    dlVer: 2,
                  },
                  lineColor: "#e99e62",
                },
              },
              wgtID: "edu.wgt.dragLine",
              wgtTitle: "Drag Line",
              styles: {
                mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                a: false,
                k: "dl$2_2",
                j: "default",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 484, y: 545 },
            shape: { type: 1, w: 20, h: 20 },
            cx: 0,
            cy: 0,
          },
        },
        "1785A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329818,
            data: {
              properties: {
                attrs: {
                  cfg: {
                    images: {
                      handle: {
                        mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                      },
                      base: {
                        mediaID: "RI1d0e79fcbc1a418c986ba7e91094d35f_png",
                      },
                    },
                    lineColor: "#e99e62",
                    lineWidth: 9,
                    basePos: "",
                    dlVer: 2,
                  },
                  lineColor: "#e99e62",
                },
              },
              wgtID: "edu.wgt.dragLine",
              wgtTitle: "Drag Line",
              styles: {
                mediaID: "RI21ccd2d935ea47ec93e715704e140598_png",
                a: false,
                k: "dl$2_3",
                j: "default",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 484, y: 720 },
            shape: { type: 1, w: 20, h: 20 },
            cx: 0,
            cy: 0,
          },
        },
        "1786A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329819,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI3ecf0157a0b24a0ea9d2d9c5e9872e6b_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$incorrect",
                c: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 152, y: 419 },
            shape: { type: 1, w: 489, h: 226 },
            cx: 0,
            cy: 0,
          },
        },
        "1787A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329820,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI1a5147ddf9a848acaaecbd75bea6f754_png",
                C: 0,
                A: "transparent",
                a: false,
                k: "i$correct",
                c: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 152, y: 419 },
            shape: { type: 1, w: 489, h: 226 },
            cx: 0,
            cy: 0,
          },
        },
        "1919A2_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329821,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.roundRect",
              wgtTitle: "Round Rectangle",
              styles: {
                O: true,
                U: true,
                F: 30,
                G: 30,
                H: 30,
                I: 30,
                A: "rgba(255,255,255,0)",
                C: 0,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1166, y: 802 },
            shape: { type: 1, w: 218, h: 71 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              order: 0,
              target: { objectID: "1937A2_" },
              set: { visibility: "Show" },
            },
          ],
        },
        "1937A2_": {
          module: "apn.CLayerContainer",
          create: {
            type: 16779780,
            zIndex: 101329822,
            data: {
              properties: { attrs: { ofl: "", Mode: "" } },
              wgtID: "apn.wgt.layerContainer",
              wgtTitle: "Multi-layer Container",
              styles: { state: "1", C: 0, k: "mlc$ox_popup", c: false },
              lockType: 0,
            },
          },
          init: {
            position: { x: 788, y: 152.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: ["1938A2_"],
            layers: { 1: { title: "Layer1", id: "1938A2_" } },
            layerIndex: 1,
          },
        },
        "1938A2_": {
          module: "apn.CLayer",
          create: { type: 16777729, zIndex: 101329823 },
          init: {
            position: { x: 788, y: 152.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
          layout: {
            children: [
              "1939A2_",
              "1944A2_",
              "2007A2_",
              "2014A2_",
              "2015A2_",
              "2011A2_",
              "2012A2_",
              "2008A2_",
              "2009A2_",
            ],
          },
        },
        "1939A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329824,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI1307b6f7912a403eb765158ec7e19428_png",
                C: 0,
                A: "transparent",
                a: false,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 788, y: 152.5 },
            shape: { type: 1, w: 670, h: 758 },
            cx: 0,
            cy: 0,
          },
        },
        "1940A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329825,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIa6403722463f460f87fb4a2ee8656abd_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$o_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 884, y: 467.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1940A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1996A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
        "1944A2_": {
          module: "apn.CRect",
          create: {
            type: 16777728,
            zIndex: 101329829,
            data: {
              properties: { ver: 2, attrs: { txtI: 0 } },
              wgtID: "apn.wgt.roundRect",
              wgtTitle: "Round Rectangle",
              styles: {
                O: true,
                U: true,
                F: 4,
                G: 4,
                H: 4,
                I: 4,
                A: "rgba(255,255,255,0)",
                C: 0,
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1387, y: 173.5 },
            shape: { type: 1, w: 51.53846153846155, h: 50 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1937A2_" },
              order: 0,
              ui: {},
              set: { visibility: "Hide" },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1940A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
              ui: {},
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2008A2_" },
              order: 2,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2011A2_" },
              order: 3,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2014A2_" },
              order: 4,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1996A2_" },
              order: 5,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2009A2_" },
              order: 6,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2012A2_" },
              order: 7,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2015A2_" },
              order: 8,
              ui: {},
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
            },
          ],
        },
        "1996A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329830,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI645b71824c7a456f913f0ac0ba15f466_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$x_1",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 977, y: 467.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1996A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "1940A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
        "2007A2_": {
          module: "bx.CEditorWnd.CGroup",
          create: { type: 16777729, zIndex: 101329831 },
          init: {
            position: { x: 884, y: 467.5 },
            shape: { type: 1, w: 177, h: 78 },
            cx: 0,
            cy: 0,
          },
          layout: { children: ["1940A2_", "1996A2_"] },
        },
        "2008A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329832,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIa6403722463f460f87fb4a2ee8656abd_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$o_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1167, y: 467.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2008A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2009A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
        "2009A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329833,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI645b71824c7a456f913f0ac0ba15f466_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$x_2",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1260, y: 467.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2009A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2008A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
        "2011A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329835,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIa6403722463f460f87fb4a2ee8656abd_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$o_3",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 884, y: 779.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2011A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2012A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
        "2012A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329836,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI645b71824c7a456f913f0ac0ba15f466_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$x_3",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 977, y: 779.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2012A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2011A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
        "2014A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329838,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RIa6403722463f460f87fb4a2ee8656abd_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$o_4",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1167, y: 779.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2014A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2015A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
        "2015A2_": {
          module: "apn.CImage",
          create: {
            type: 16777728,
            zIndex: 101329839,
            data: {
              properties: { attrs: { cfg: { mr: 0 } } },
              wgtID: "apn.wgt.image2",
              wgtTitle: "Image",
              styles: {
                mediaID: "RI645b71824c7a456f913f0ac0ba15f466_png",
                C: 0,
                A: "transparent",
                a: false,
                Y: "0.00",
                j: "pointer",
                k: "i$x_4",
              },
              lockType: 0,
            },
          },
          init: {
            position: { x: 1260, y: 779.5 },
            shape: { type: 1, w: 84, h: 78 },
            cx: 0,
            cy: 0,
          },
          ITRs: [
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2015A2_" },
              set: { alpha: 1 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 0,
            },
            {
              action: "CWP",
              event: "tapStart",
              target: { objectID: "2014A2_" },
              set: { alpha: 0 },
              timing: { roundUp: false, wait: 0, duration: 0 },
              order: 1,
            },
          ],
        },
      },
      module: "apn.CFlowPage",
      BG: { fillStyle: "#ffffff" },
      SPT: {
        spt_EvtBubble:
          'if (!Event.target) {\n  if (Event.type == "Page Create") {\n    onPageCreate();\n  } else if (Event.type == "Page Run") {\n    onPageRun();\n  }\n} else {\n  var label = Event.target.get("label");\n  if (Event.type == "Drag Start") {\n    onDragStart();\n  } else if (Event.type == "Drop Result") {\n    onDropResult();\n  } else if (Event.type == "Drop") {\n    onDrop();\n  } else if (Event.type == "Tap Start") {\n    if (label == "rr$line_exit") {\n      onTapPopupExit();\n    } else if(label.indexOf("i$reset_") >-1 ) {\n      onTapPopupExit();\n    }\n  }\n}\n\n// Page Craete\nfunction onPageCreate() {\n  $W("dl$", undefined, { multiple: true, like: true }).forEach(function (drag) {\n    drag.local.origin = {\n      x: drag.get("x"),\n      y: drag.get("y"),\n    };\n  });\n\n  $W("ia$", undefined, { multiple: true, like: true }).forEach(function (\n    dropZone\n  ) {\n    dropZone.acceptEvent("Drop", true);\n  });\n}\n\n// Page Run\nfunction onPageRun() {\n  set("$incorrect", false);\n  set("$drop:count", 0);\n}\n\n// 드래그 시작\nfunction onDragStart() {\n  var target = Event.target;\n  var targetNum = target.get("label").split("$")[1].split("_")[0];\n\n  $W("ia$", undefined, { multiple: true, like: true }).forEach(function (\n    dropZone\n  ) {\n    if (dropZone.get("label").split("$")[1].split("_")[0] == targetNum) {\n      dropZone.set("visibility", "visible");\n    } else {\n      dropZone.set("visibility", "hidden");\n    }\n  });\n  target.zIndexTo("Top");\n  set("$drag", target);\n}\n\n// 드랍 범위 외 드랍 시\nfunction onDropResult() {\n  var target = Event.target;\n  var targetNum = target.get("label").split("_")[1];\n  setOriginTarget(target);\n  set("$drag", null);\n}\n\n// 드랍 범위에 드랍 시\nfunction onDrop() {\n  var target = Event.target;\n  var targetNum = target.get("label").split("_")[1];\n\n  if (target.local.drop) {\n    setOriginTarget(get("$drag"));\n    return;\n  }\n\n  target.local.drop = true;\n\n  if (\n    get("$drag").get("label").split("_")[1] != target.get("label").split("_")[1]\n  ) {\n    set("$incorrect", true);\n  }\n\n  get("$drag").moveTo(getCenterPos(target).x - 10, getCenterPos(target).y - 10);\n  get("$drag").set("visibility", "visibleEventPass");\n  onCheckCorrect();\n}\n\n// 선잇기 팝업 종료 및 초기화\nfunction onTapPopupExit() {\n  set("$incorrect", false);\n  set("$drop:count", 0);\n  $W("ia$", undefined, { multiple: true, like: true }).forEach(function (\n    dropZone\n  ) {\n    dropZone.local.drop = false;\n    dropZone.acceptEvent("Drop", true);\n    dropZone.set("visibility", "visible");\n  });\n  $W("dl$", undefined, { multiple: true, like: true }).forEach(function (drag) {\n    drag.set("visibility", "visible");\n    setOriginTarget(drag);\n  });\n  $W("i$correct").set("visibility", "hidden");\n  $W("i$incorrect").set("visibility", "hidden");\n  $W("i$reset_1").set("visibility","visibleEventPass");\n}\n\n// 원래 자리로 이동\nfunction setOriginTarget(target) {\n  target.moveTo(target.local.origin.x, target.local.origin.y);\n  $W("ia$", undefined, { multiple: true, like: true }).forEach(function (\n    dropZone\n  ) {\n    dropZone.set("visibility", "hidden");\n  });\n}\n\n// 정답 확인\nfunction onCheckCorrect() {\n  set("$drop:count", get("$drop:count") + 1);\n  if (get("$drop:count") === 3) {\n    if (get("$incorrect")) {\n      $W("i$incorrect").set("visibility", "visible");\n    } else {\n      $W("i$correct").set("visibility", "visible");\n    }\n    $W("i$reset_1").set("visibility","visible");\n  }\n}\n\n/**\n * 위젯의 가운데 좌표를 반환\n *\n * @param {Widget} widget 해당 위젯\n *\n * @returns {object} obj\n *          {int} obj.x x좌표\n *          {int} obj.y y좌표\n *\n */\nfunction getCenterPos(widget) {\n  return {\n    x: widget.get("x") + widget.get("w") / 2,\n    y: widget.get("y") + widget.get("h") / 2,\n  };\n}\n\n/**\n * 위젯의 중간 좌표를 기준으로 상대 위젯 안에 위치해 있는지 확인\n *\n * @param {Widget} widget 해당 위젯\n * @param {Widget} areaWgt 영역 위젯\n *\n * @returns {boolean} 영역 안에 있는지 여부\n *\n */\nfunction checkInArea(widget, areaWgt) {\n  var dragPos = getCenterPos(widget);\n  var areaPos = {\n    widthLeft: areaWgt.get("x"),\n    widthRight: areaWgt.get("x") + areaWgt.get("w"),\n    heightTop: areaWgt.get("y"),\n    heightBottom: areaWgt.get("y") + areaWgt.get("h"),\n  };\n  return (\n    dragPos.x > areaPos.widthLeft &&\n    dragPos.x < areaPos.widthRight &&\n    dragPos.y > areaPos.heightTop &&\n    dragPos.y < areaPos.heightBottom\n  );\n}\n',
      },
    },
    S: {
      UI: { title: "START", noEditable: true },
      objects: {},
      module: "apn.CFlowStartPage",
      ITRs: [
        {
          event: "flickLeft",
          action: "LTP",
          from: { objectID: "$SP", pageID: "S" },
          to: { pageID: "1", type: "1" },
          transit: {},
        },
      ],
    },
    E: {
      UI: { title: "OUT", noEditable: true },
      objects: {},
      module: "apn.CFlowEndPage",
    },
    I: {
      UI: { title: "IN", noEditable: true },
      objects: {},
      module: "apn.CFlowInPage",
    },
    C: {
      UI: { title: "CLIENT", noEditable: true },
      objects: {},
      module: "apn.CFlow2ndStartPage",
    },
  },
  layouts: {
    1: {
      CTXT: { deviceID: "EDU", wgtLibID: "EDU", exeID: "standard" },
      property: {
        screenSize: { w: 1531, h: 984 },
        styles: {
          normal: {
            fontStyle: "#000000",
            fontStrokeStyle: "#FFA500",
            fontStrokeWidth: 0,
            font: "Arial",
            fontSize: "24px",
            textAlign: "center",
            textValign: "middle",
            fillStyle: "#FFFFFF",
            strokeStyle: "#7E7E7E",
            lineWidth: 1,
            lineDash: null,
            lineEnd: "square",
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            angle: 0,
            title: "",
            visibility: true,
            alpha: 1,
            dragX: false,
            dragY: false,
            dragInParent: false,
            dragContainParent: false,
            csr: "apn.auto",
            fontItalic: false,
            fontBold: false,
            fontUnderlined: false,
            ltrSp: 0,
            lnSp: 0,
            textMultiLine: false,
            textWordWrap: true,
            text: "",
          },
        },
        properties: { exeScript: 2 },
        skinID: "Apple",
        themeID: "EDU",
        skinShow: 1,
        CExe: {
          layout: {
            layout: "C",
            padding: { left: 0, right: 0, top: 0, bottom: 0, ofl: "" },
            style: { bgImgPtn: "tile", bgImg: {}, bgClr: null },
          },
          enhcTxt: "Y",
          loading: {
            type: "",
            img: { type: "" },
            spinner: { type: "roller1", strokeClr: null },
          },
          event: { TS1: "", PE: "", SL: "" },
          inputSave: "",
          inputTextScroll: "",
          inputDisableTabOrder: "",
          lng: { ime: "" },
          edtOpts: { keepLabelOnCopy: "", useGroupProp: "" },
          pageOutline: {
            radius: [{ LT: 0, LB: 0, RT: 0, RB: 0 }],
            shadow: [{ x: 0, y: 0, spread: 0, color: null }],
          },
          scBar: {
            clrThumb: "#7f7f7f",
            clrThumbHover: "#7f7f7f",
            clrTrack: "#dddddd",
            cRdr: "50%",
            noCustom: "",
          },
          splash: { img: {}, bgClr: null, w: 40 },
          brTm: { frameClr: null },
          spt2impt: {
            js: [{ name: "", lnP: "", lnE: "" }],
            media: [{ key: "", cmt: "", md: {} }],
            mediaA: [{ key: "", cmt: "", md: {} }],
          },
          spt2preq: [{ json: { size: 0, data: "" } }],
          mdLD: { type: "" },
          vdStrictPlay: "",
          apCH: { acnt: 0, vcnt: 0 },
          mediaOnHidden: "",
          js: { fs: [{ js: { size: 0, data: "" }, v: "", c: "" }] },
          pubDateUpdate: "",
          pubFonts: [{ face: "", path: "" }],
          customPath: { core: "" },
          exFonts: [
            {
              title: "ExampleFont",
              face: "",
              ln: "en",
              noBold: "Y",
              path: "http://fonts.googleapis.com/earlyaccess/nanum.css",
              pathL: "../../../share/font/Nanum/font.css",
              pathL2: "",
            },
          ],
          exFontsPub: "",
          sns: { ogI: "", ogT: "", ogD: "", srD: "" },
          prvMode: { urlPrm: "" },
          apxTdata: [
            {
              data: {
                st: [
                  { t: "Name", c: "", o: "", type: "text", w: 0, apxIndex: 1 },
                ],
                data: {
                  idx: 2,
                  st: {
                    1: {
                      t: "Name",
                      c: "",
                      o: "",
                      type: "text",
                      w: 0,
                      apxIndex: 1,
                    },
                  },
                  tbl: [{ 1: "" }],
                  maxCount: 0,
                  o: "",
                },
              },
              desc: "",
              id: "",
              type: "",
            },
          ],
          apxTdataF: [
            {
              id: " Duplicated1",
              type: "",
              desc: "",
              json: { size: 0, data: "" },
            },
          ],
          apxTdataDesc: "",
        },
      },
      pages: {},
    },
  },
  flow: {
    pages: {
      1: { init: { position: { x: -1792, y: 256 } } },
      2: { init: { position: { x: 896, y: 1280 } } },
      S: { init: { position: { x: 794.75, y: 173.75 } } },
    },
  },
  index: { pageID: 8, layoutID: 2, rscID: 445898361 },
  rsc: {},
};
